//
//  The MIT License (MIT)
//
//  Copyright (c) 2016 Srdan Rasic (@srdanrasic)
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.
//

// MARK: - StreamEventType

/// Represents a stream event.
public protocol StreamEventType: EventType {
}

// MARK: - StreamEvent

/// Represents a stream event.
public enum StreamEvent<T>: StreamEventType {

  /// The type of elements generated by the stream.
  public typealias Element = T

  /// Contains element.
  case Next(T)

  /// Stream is completed.
  case Completed

  /// Create new `.Next` event.
  public static func next(_ element: T) -> StreamEvent<Element> {
    return .Next(element)
  }

  /// Create new `.Completed` event.
  public static func completed() -> StreamEvent<Element> {
    return .Completed
  }

  /// Extract an element from a non-terminal (`.Next`) event.
  public var element: Element? {
    switch self {
    case .Next(let element):
      return element
    default:
      return nil
    }
  }

  /// Does the event mark failure of a stream? Always `False` for `StreamEvent`.
  public var isFailure: Bool {
    return false
  }

  /// Does the event mark completion of a stream? `True` if event is `.Completion`.
  public var isCompletion: Bool {
    switch self {
    case .Next:
      return false
    case .Completed:
      return true
    }
  }
}

// MARK: - StreamEventType Extensions

public extension StreamEventType {

  public var unbox: StreamEvent<Element> {
    if let element = element {
      return StreamEvent.Next(element)
    } else {
      return StreamEvent.Completed
    }
  }

  public func map<U>(_ transform: (Element) -> U) -> StreamEvent<U> {
    switch self.unbox {
    case .Next(let value):
      return .Next(transform(value))
    case .Completed:
      return .Completed
    }
  }
}

// MARK: - StreamType

/// Represents a stream over generic Element type.
public protocol StreamType: _StreamType {

  /// The type of elements generated by the stream.
  associatedtype Element

  /// Underlying raw stream. Stream is just a wrapper over `RawStream` that
  /// operates on events of `StreamEvent` type.
  var rawStream: RawStream<StreamEvent<Element>> { get }

  /// Register an observer that will receive events from the stream. Registering
  /// an observer starts the stream. Disposing the returned disposable can
  /// be used to cancel (stop) the stream.
  func observe(observer: @escaping (StreamEvent<Element>) -> Void) -> Disposable
}

public extension StreamType {

  /// Transform the stream by transforming underlying raw stream.
  public func lift<U>(transform: @escaping (RawStream<StreamEvent<Element>>) -> RawStream<StreamEvent<U>>) -> Stream<U> {
    return Stream<U> { observer in
      return transform(self.rawStream).observe(observer: observer.observer)
    }
  }

  /// Register an observer that will receive events from the stream. Registering
  /// an observer starts the stream. Disposing the returned disposable can
  /// be used to cancel (stop) the stream.
  public func observe(observer: @escaping (StreamEvent<Element>) -> Void) -> Disposable {
    return rawStream.observe(observer: observer)
  }
}

extension StreamEvent: CustomStringConvertible {

  public var description: String {
    switch self {
    case .Next(let element):
      return ".Next(\(element))"
    case .Completed:
      return ".Completed"
    }
  }
}

// MARK: - Stream

/// Represents a stream over generic Element type.
/// Well-formed streams conform to the grammar: `Next* Completed`.
public struct Stream<T>: StreamType {

  /// The type of elements generated by the stream.
  public typealias Element = T

  public typealias Event = StreamEvent<T>

  /// Underlying raw stream. Stream is just a wrapper over `RawStream` that
  /// operates on events of `StreamEvent` type.
  public let rawStream: RawStream<StreamEvent<T>>

  /// Create a new stream from a raw stream.
  public init(rawStream: RawStream<StreamEvent<T>>) {
    self.rawStream = rawStream
  }

  /// Create a new stream using a producer.
  public init(producer: @escaping (Observer<Event>) -> Disposable) {
    rawStream = RawStream(producer: producer)
  }
}

// MARK: - Extensions

// MARK: Creating a stream

public extension Stream {

  /// Create a stream that emits given element and then completes.
  public static func just(_ element: Element) -> Stream<Element> {
    return Stream { observer in
      observer.next(element)
      observer.completed()
      return NotDisposable
    }
  }

  /// Create a stream that emits given sequence of elements and then completes.
  public static func sequence<S: Sequence>(_ sequence: S) -> Stream<Element> where S.Iterator.Element == Element {
    return Stream { observer in
      sequence.forEach(observer.next)
      observer.completed()
      return NotDisposable
    }
  }

  /// Create a stream that completes without emitting any elements.
  public static func completed() -> Stream<Element> {
    return Stream { observer in
      observer.completed()
      return NotDisposable
    }
  }

  /// Create an stream that never completes.
  public static func never() -> Stream<Element> {
    return Stream { observer in
      return NotDisposable
    }
  }

  /// Create a stream that emits an integer every `interval` time on a given queue.
  public static func interval(_ interval: TimeValue, queue: DispatchQueue) -> Stream<Int> {
    return Stream<Int>(rawStream: RawStream.interval(interval, queue: queue))
  }

  /// Create a stream that emits given element after `time` time on a given queue.
  public static func timer(element: Element, time: TimeValue, queue: DispatchQueue) -> Stream<Element> {
    return Stream<Element>(rawStream: RawStream.timer(events: [.Next(element), .Completed], time: time, queue: queue))
  }
}

// MARK: Transforming stream

public extension StreamType {

  /// Batch the elements into arrays of given size.
  public func buffer(size: Int) -> Stream<[Element]> {
    return Stream { observer in
      var buffer: [Element] = []
      return self.observe { event in
        switch event {
        case .Next(let element):
          buffer.append(element)
          if buffer.count == size {
            observer.next(buffer)
            buffer.removeAll()
          }
        case .Completed:
          observer.completed()
        }
      }
    }
  }

  /// Map each event into a stream and then flatten those streams using
  /// the given flattening strategy.
  public func flatMap<U: StreamType>(strategy: FlatMapStrategy, transform: @escaping (Element) -> U) -> Stream<U.Element> {
    let transform: (Element) -> Stream<U.Element> = { transform($0).toStream() }
    switch strategy {
    case .Latest:
      return map(transform).switchToLatest()
    case .Merge:
      return map(transform).merge()
    case .Concat:
      return map(transform).concat()
    }
  }

  /// Map each event into an stream and then flattens inner streams.
  public func flatMapLatest<U: StreamType>(transform: @escaping (Element) -> U) -> Stream<U.Element> {
    return flatMap(strategy: .Latest, transform: transform)
  }

  /// Map each event into an stream and then flattens inner streams.
  public func flatMapMerge<U: StreamType>(transform: @escaping (Element) -> U) -> Stream<U.Element> {
    return flatMap(strategy: .Merge, transform: transform)
  }

  /// Map each event into an stream and then flattens inner streams.
  public func flatMapConcat<U: StreamType>(transform: @escaping (Element) -> U) -> Stream<U.Element> {
    return flatMap(strategy: .Concat, transform: transform)
  }

  /// Map each event into an operation and then flatten those operation using
  /// the given flattening strategy.
  public func flatMap<U: OperationType>(strategy: FlatMapStrategy, transform: @escaping (Element) -> U) -> Operation<U.Element, U.ErrorType> {
    let transform: (Element) -> Operation<U.Element, U.ErrorType> = { transform($0).toOperation() }
    switch strategy {
    case .Latest:
      return map(transform).switchToLatest()
    case .Merge:
      return map(transform).merge()
    case .Concat:
      return map(transform).concat()
    }
  }

  /// Map each event into an operation and then flattens inner operations.
  public func flatMapLatest<U: OperationType>(transform: @escaping (Element) -> U) -> Operation<U.Element, U.ErrorType> {
    return flatMap(strategy: .Latest, transform: transform)
  }

  /// Map each event into an operation and then flattens inner operations.
  public func flatMapMerge<U: OperationType>(transform: @escaping (Element) -> U) -> Operation<U.Element, U.ErrorType> {
    return flatMap(strategy: .Merge, transform: transform)
  }

  /// Map each event into an operation and then flattens inner operations.
  public func flatMapConcat<U: OperationType>(transform: @escaping (Element) -> U) -> Operation<U.Element, U.ErrorType> {
    return flatMap(strategy: .Concat, transform: transform)
  }

  /// Transform each element by applying `transform` on it.
  public func map<U>(_ transform: @escaping (Element) -> U) -> Stream<U> {
    return lift { stream in
      stream.map { event in
        return event.map(transform)
      }
    }
  }

  /// Maps elements to Void.
  public func eraseType() -> Stream<Void> {
    return map { _ in }
  }

  /// Apply `combine` to each element starting with `initial` and emit each
  /// intermediate result. This differs from `reduce` which emits only final result.
  public func scan<U>(_ initial: U, _ combine: @escaping (U, Element) -> U) -> Stream<U> {
    return lift { stream in
      return stream.scan(.Next(initial)) { memo, new in
        switch new {
        case .Next(let element):
          return .Next(combine(memo.element!, element))
        case .Completed:
          return .Completed
        }
      }
    }
  }

  /// Transform each element by applying `transform` on it.
  public func tryMap<U, ErrorType>(transform: @escaping (Element) -> Result<U, ErrorType>) -> Operation<U, ErrorType> {
    return toOperation().tryMap(transform)
  }

  /// Convert the stream to an operation.
  public func toOperation<E: Error>() -> Operation<Element, E> {
    return Operation { observer in
      return self.observe { event in
        switch event {
        case .Next(let element):
          observer.next(element)
        case .Completed:
          observer.completed()
        }
      }
    }
  }

  /// Convert the stream to a concrete stream.
  public func toStream() -> Stream<Element> {
    return Stream(rawStream: self.rawStream)
  }

  /// Batch each `size` elements into another stream.
  public func window(size: Int) -> Stream<Stream<Element>> {
    return buffer(size: size).map { Stream.sequence($0) }
  }
}

// MARK: Filtration

extension StreamType {

  /// Emit an element only if `interval` time passes without emitting another element.
  public func debounce(interval: TimeValue, on queue: DispatchQueue) -> Stream<Element> {
    return lift { $0.debounce(interval: interval, on: queue) }
  }

  /// Emit first element and then all elements that are not equal to their predecessor(s).
  public func distinct(areDistinct: @escaping (Element, Element) -> Bool) -> Stream<Element> {
    return lift { $0.distinct(areDistinct: areDistinct) }
  }

  /// Emit only element at given index if such element is produced.
  public func element(at index: Int) -> Stream<Element> {
    return lift { $0.element(at: index) }
  }

  /// Emit only elements that pass `include` test.
  public func filter(include: @escaping (Element) -> Bool) -> Stream<Element> {
    return lift { $0.filter { $0.element.flatMap(include) ?? true } }
  }

  /// Emit only the first element generated by the stream and then complete.
  public func first() -> Stream<Element> {
    return lift { $0.first() }
  }

  /// Ignore all elements (just propagate terminal events).
  public func ignoreElements() -> Stream<Element> {
    return lift { $0.ignoreElements() }
  }

  /// Emit only last element generated by the stream and then complete.
  public func last() -> Stream<Element> {
    return lift { $0.last() }
  }

  /// Periodically sample the stream and emit latest element from each interval.
  public func sample(interval: TimeValue, on queue: DispatchQueue) -> Stream<Element> {
    return lift { $0.sample(interval: interval, on: queue) }
  }

  /// Suppress first `count` elements generated by the stream.
  public func skip(first count: Int) -> Stream<Element> {
    return lift { $0.skip(first: count) }
  }

  /// Suppress last `count` elements generated by the stream.
  public func skip(last count: Int) -> Stream<Element> {
    return lift { $0.skip(last: count) }
  }

  /// Emit only first `count` elements of the stream and then complete.
  public func take(first count: Int) -> Stream<Element> {
    return lift { $0.take(first: count) }
  }

  /// Emit only last `count` elements of the stream and then complete.
  public func take(last count: Int) -> Stream<Element> {
    return lift { $0.take(last: count) }
  }

  /// Throttle the stream to emit at most one element per given `seconds` interval.
  public func throttle(seconds: TimeValue) -> Stream<Element> {
    return lift { $0.throttle(seconds: seconds) }
  }
}

extension StreamType where Element: Equatable {

  /// Emit first element and then all elements that are not equal to their predecessor(s).
  public func distinct() -> Stream<Element> {
    return lift { $0.distinct() }
  }
}

public extension StreamType where Element: OptionalType, Element.Wrapped: Equatable {

  /// Emit first element and then all elements that are not equal to their predecessor(s).
  public func distinct() -> Stream<Element> {
    return lift { $0.distinct() }
  }
}

public extension StreamType where Element: OptionalType {

  /// Suppress all `nil`-elements.
  public func ignoreNil() -> Stream<Element.Wrapped> {
    return Stream { observer in
      return self.observe { event in
        switch event {
        case .Next(let element):
          if let element = element._unbox {
            observer.next(element)
          }
        case .Completed:
          observer.completed()
        }
      }
    }
  }
}

// MARK: Combination

extension StreamType {

  /// Emit a pair of latest elements from each stream. Starts when both streams
  /// emit at least one element, and emits `.Next` when either stream generates an element.
  public func combineLatest<S: StreamType>(with other: S) -> Stream<(Element, S.Element)> {
    return lift {
      return $0.combineLatest(with: other.toStream()) { myLatestElement, my, theirLatestElement, their, isMy in
        switch (my, their) {
        case (.Completed, .Completed):
          return StreamEvent.Completed
        case (.Next(let myElement), .Next(let theirElement)):
          return StreamEvent.Next(myElement, theirElement)
        case (.Next(let myElement), .Completed):
          if let theirLatestElement = theirLatestElement, isMy {
            return StreamEvent.Next(myElement, theirLatestElement)
          } else {
            return nil
          }
        case (.Completed, .Next(let theirElement)):
          if let myLatestElement = myLatestElement {
            return StreamEvent.Next(myLatestElement, theirElement)
          } else {
            return nil
          }
        }
      }
    }
  }

  /// Merge emissions from both source and `other` into one stream.
  public func merge<S: StreamType>(with other: S) -> Stream<Element> where S.Element == Element {
    return lift { $0.merge(with: other.rawStream) }
  }

  /// Prepend given element to the operation emission.
  public func start(with element: Element) -> Stream<Element> {
    return lift { $0.start(with: .Next(element)) }
  }

  /// Emit elements from source and `other` in pairs. This differs from `combineLatestWith` in
  /// that pairs are produced from elements at same positions.
  public func zip<S: StreamType>(with other: S) -> Stream<(Element, S.Element)> {
    return lift {
      return $0.zip(with: other.toStream()) { my, their in
        switch (my, their) {
        case (.Next(let myElement), .Next(let theirElement)):
          return StreamEvent.Next(myElement, theirElement)
        case (_, .Completed):
          return StreamEvent.Completed
        case (.Completed, _):
          return StreamEvent.Completed
        default:
          fatalError("This will never execute: Swift compiler cannot infer switch completeness.")
        }
      }
    }
  }

  /// Combines two streams into a stream of pairs of elements whenever the receiver emits an element with the latest element from the given stream.
  public func withLatest<S: StreamType>(from other: S) -> Stream<(Element, S.Element)> {
    return lift {
      return $0.combineLatest(with: other.toStream()) { myLatestElement, my, theirLatestElement, their, isMy in
        switch (my, their) {
        case (.Completed, _):
          return StreamEvent.Completed
        case (.Next(let myElement), .Next(let theirElement)):
          guard isMy else { return nil }
          return StreamEvent.Next(myElement, theirElement)
        case (.Next(let myElement), .Completed):
          guard isMy else { return nil }
          if let theirLatestElement = theirLatestElement {
            return StreamEvent.Next(myElement, theirLatestElement)
          } else {
            return nil
          }
        }
      }
    }
  }
}

//  MARK: Utilities

extension StreamType {

  /// Set the execution context in which to execute the stream (i.e. in which to run
  /// the stream's producer).
  public func executeIn(_ context: @escaping ExecutionContext) -> Stream<Element> {
    return lift { $0.executeIn(context) }
  }

  /// Delay stream events for `interval` time.
  public func delay(interval: TimeValue, on queue: DispatchQueue) -> Stream<Element> {
    return lift { $0.delay(interval: interval, on: queue) }
  }

  /// Do side-effect upon various events.
  public func doOn(next: ((Element) -> ())? = nil,
                   start: (() -> Void)? = nil,
                   completed: (() -> Void)? = nil,
                   disposed: (() -> ())? = nil) -> Stream<Element> {
    return Stream { observer in
      start?()
      let disposable = self.observe { event in
        switch event {
        case .Next(let value):
          next?(value)
        case .Completed:
          completed?()
        }
        observer.observer(event)
      }
      return BlockDisposable {
        disposable.dispose()
        disposed?()
      }
    }
  }

  /// Use `doOn` to log various events.
  public func debug(id: String = "Untitled Stream") -> Stream<Element> {
    return doOn(next: { element in
        print("\(id): Next(\(element))")
      }, start: {
        print("\(id): Start")
      }, completed: {
        print("\(id): Completed")
      }, disposed: {
        print("\(id): Disposed")
      })
  }

  /// Set the execution context in which to dispatch events (i.e. in which to run observers).
  public func observeIn(_ context: @escaping ExecutionContext) -> Stream<Element> {
    return lift { $0.observeIn(context) }
  }

  /// Supress non-terminal events while last event generated on other stream is `false`.
  public func pausable<S: _StreamType>(by other: S) -> Stream<Element> where S.Event.Element == Bool {
    return lift { $0.pausable(by: other) }
  }
}

// MARK: Injections

extension StreamType {

  /// Updates the given subject with `true` when the receiver starts and with `false` when the receiver terminates.
  public func feedActivityInto<S: SubjectType>(listener: S) -> Stream<Element> where S.Event.Element == Bool {
    return doOn(start: { listener.next(true) }, disposed: { listener.next(false) })
  }

  /// Updates the given subject with .Next elements.
  public func feedNextInto<S: SubjectType>(listener: S) -> Stream<Element> where S.Event.Element == Element {
    return doOn(next: { e in listener.next(e) })
  }

  /// Updates the given subject with mapped .Next element whenever the element satisfies the given constraint.
  public func feedNextInto<S: SubjectType>(listener: S, when: @escaping (Element) -> Bool = { _ in true }, map: @escaping (Element) -> S.Event.Element) -> Stream<Element> {
    return doOn(next: { e in if when(e) { listener.next(map(e)) } })
  }
}

// MARK: Conditional, Boolean and Aggregational

extension StreamType {

  /// Propagate event only from a stream that starts emitting first.
  public func amb<S: StreamType>(with other: S) -> Stream<Element> where S.Element == Element {
    return lift { $0.amb(with: other.rawStream) }
  }

  /// Collect all elements into an array and emit just that array.
  public func collect() -> Stream<[Element]> {
    return reduce([], { memo, new in memo + [new] })
  }

  /// First emit events from source and then from `other` stream.
  public func concat<S: StreamType>(with other: S) -> Stream<Element> where S.Element == Element {
    return lift { stream in
      stream.concat(with: other.rawStream)
    }
  }

  /// Emit default element is the stream completes without emitting any element.
  public func defaultIfEmpty(_ element: Element) -> Stream<Element> {
    return lift { $0.defaultIfEmpty(element) }
  }

  /// Reduce elements to a single element by applying given function on each emission.
  public func reduce<U>(_ initial: U, _ combine: @escaping (U, Element) -> U) -> Stream<U> {
    return Stream<U> { observer in
      observer.next(initial)
      return self.scan(initial, combine).observe(observer: observer.observer)
    }.last()
  }

  /// Par each element with its predecessor. First element is paired with `nil`.
  public func zipPrevious() -> Stream<(Element?, Element)> {
    return Stream { observer in
      var previous: Element? = nil
      return self.observe { event in
        switch event {
        case .Next(let element):
          observer.next((previous, element))
          previous = element
        case .Completed:
          observer.completed()
        }
      }
    }
  }
}

// MARK: Streams that emit other streams

public extension StreamType where Element: StreamType, Element.Event: StreamEventType {

  public typealias InnerElement = Element.Event.Element

  /// Flatten the stream by observing all inner streams and propagate elements from each one as they come.
  public func merge() -> Stream<InnerElement> {
    return lift { stream in
      return stream.merge(unboxEvent: { $0.unbox }, propagateErrorEvent: { _, _ in })
    }
  }

  /// Flatten the stream by observing and propagating emissions only from the latest inner stream.
  public func switchToLatest() -> Stream<InnerElement> {
    return lift { stream in
      return stream.switchToLatest(unboxEvent: { $0.unbox }, propagateErrorEvent: { _, _ in })
    }
  }

  /// Flatten the stream by sequentially observing inner streams in order in
  /// which they arrive, starting next observation only after the previous one completes.
  public func concat() -> Stream<InnerElement> {
    return lift { stream in
      return stream.concat(unboxEvent: { $0.unbox }, propagateErrorEvent: { _, _ in })
    }
  }
}

// MARK: Streams that emit operations

public extension StreamType where Element: OperationType, Element.Event: OperationEventType {
  public typealias InnerOperationElement = Element.Event.Element
  public typealias InnerOperationError = Element.Event.ErrorType

  /// Flatten the stream by observing all inner operation and propagate elements from each one as they come.
  public func merge() -> Operation<InnerOperationElement, InnerOperationError> {
    return self.toOperation().merge()
  }

  /// Flatten the stream by observing and propagating emissions only from the latest inner operation, cancelling previous one when new one starts.
  public func switchToLatest() -> Operation<InnerOperationElement, InnerOperationError> {
    return self.toOperation().switchToLatest()
  }

  /// Flatten the stream by sequentially observing inner operations in order in
  /// which they arrive, starting next observation only after the previous one completes.
  public func concat() -> Operation<InnerOperationElement, InnerOperationError> {
    return self.toOperation().switchToLatest()
  }
}

// MARK: Connectable

extension StreamType {

  /// Ensure that all observers see the same sequence of elements. Connectable.
  public func replay(_ limit: Int = Int.max) -> ConnectableStream<Element> {
    return ConnectableStream(rawConnectableStream: rawStream.replay(limit))
  }

  /// Convert the stream to a connectable stream.
  public func publish() -> ConnectableStream<Element> {
    return ConnectableStream(rawConnectableStream: rawStream.publish())
  }

  /// Ensure that all observers see the same sequence of elements. 
  /// Shorthand for `replay(limit).refCount()`.
  public func shareReplay(_ limit: Int = Int.max) -> Stream<Element> {
    return replay(limit).refCount()
  }
}

// MARK: Functions

/// Combine multiple streams into one. See `mergeWith` for more info.
public func combineLatest
  <A: StreamType,
   B: StreamType>
  (_ a: A, _ b: B) -> Stream<(A.Element, B.Element)> {
  return a.combineLatest(with: b)
}

/// Combine multiple operations into one. See `mergeWith` for more info.
public func combineLatest
  <A: StreamType,
   B: StreamType,
   C: StreamType>
  (_ a: A, _ b: B, _ c: C) -> Stream<(A.Element, B.Element, C.Element)> {
  return combineLatest(a, b).combineLatest(with: c).map { ($0.0, $0.1, $1) }
}

/// Combine multiple operations into one. See `mergeWith` for more info.
public func combineLatest
  <A: StreamType,
   B: StreamType,
   C: StreamType,
   D: StreamType>
  (_ a: A, _ b: B, _ c: C, _ d: D) -> Stream<(A.Element, B.Element, C.Element, D.Element)> {
  return combineLatest(a, b, c).combineLatest(with: d).map { ($0.0, $0.1, $0.2, $1) }
}

/// Combine multiple operations into one. See `mergeWith` for more info.
public func combineLatest
  <A: StreamType,
   B: StreamType,
   C: StreamType,
   D: StreamType,
   E: StreamType>
  (_ a: A, _ b: B, _ c: C, _ d: D, _ e: E) -> Stream<(A.Element, B.Element, C.Element, D.Element, E.Element)> {
  return combineLatest(a, b, c, d).combineLatest(with: e).map { ($0.0, $0.1, $0.2, $0.3, $1) }
}

/// Combine multiple operations into one. See `mergeWith` for more info.
public func combineLatest
  <A: StreamType,
   B: StreamType,
   C: StreamType,
   D: StreamType,
   E: StreamType,
   F: StreamType>
  (_ a: A, _ b: B, _ c: C, _ d: D, _ e: E, _ f: F) -> Stream<(A.Element, B.Element, C.Element, D.Element, E.Element, F.Element)> {
  return combineLatest(a, b, c, d, e).combineLatest(with: f).map { ($0.0, $0.1, $0.2, $0.3, $0.4, $1) }
}

/// Zip multiple operations into one. See `zipWith` for more info.
public func zip
  <A: StreamType,
   B: StreamType>
  (_ a: A, _ b: B) -> Stream<(A.Element, B.Element)> {
  return a.zip(with: b)
}

/// Zip multiple operations into one. See `zipWith` for more info.
public func zip
  <A: StreamType,
   B: StreamType,
   C: StreamType>
  (_ a: A, _ b: B, _ c: C) -> Stream<(A.Element, B.Element, C.Element)> {
  return zip(a, b).zip(with: c).map { ($0.0, $0.1, $1) }
}

/// Zip multiple operations into one. See `zipWith` for more info.
public func zip
  <A: StreamType,
   B: StreamType,
   C: StreamType,
   D: StreamType>
  (_ a: A, _ b: B, _ c: C, _ d: D) -> Stream<(A.Element, B.Element, C.Element, D.Element)> {
  return zip(a, b, c).zip(with: d).map { ($0.0, $0.1, $0.2, $1) }
}

/// Zip multiple operations into one. See `zipWith` for more info.
public func zip
  <A: StreamType,
   B: StreamType,
   C: StreamType,
   D: StreamType,
   E: StreamType>
  (_ a: A, _ b: B, _ c: C, _ d: D, _ e: E) -> Stream<(A.Element, B.Element, C.Element, D.Element, E.Element)> {
  return zip(a, b, c, d).zip(with: e).map { ($0.0, $0.1, $0.2, $0.3, $1) }
}

/// Zip multiple operations into one. See `zipWith` for more info.
public func zip
  <A: StreamType,
   B: StreamType,
   C: StreamType,
   D: StreamType,
   E: StreamType,
   F: StreamType>
  (_ a: A, _ b: B, _ c: C, _ d: D, _ e: E, _ f: F) -> Stream<(A.Element, B.Element, C.Element, D.Element, E.Element, F.Element)> {
  return zip(a, b, c, d, e).zip(with: f).map { ($0.0, $0.1, $0.2, $0.3, $0.4, $1) }
}

// MARK: - ConnectableStream

/// Represents a stream that is started by calling `connect` on it.
public class ConnectableStream<T>: StreamType {
  public typealias Event = StreamEvent<T>

  fileprivate let rawConnectableStream: RawConnectableStream<RawStream<Event>>

  public var rawStream: RawStream<StreamEvent<T>> {
    return rawConnectableStream.toRawStream()
  }

  fileprivate init(rawConnectableStream: RawConnectableStream<RawStream<Event>>) {
    self.rawConnectableStream = rawConnectableStream
  }

  /// Register an observer that will receive events from the stream.
  /// Note that the events will not be generated until `connect` is called.
  public func observe(observer: @escaping (Event) -> Void) -> Disposable {
    return rawConnectableStream.observe(observer: observer)
  }

  /// Start the stream.
  public func connect() -> Disposable {
    return rawConnectableStream.connect()
  }
}

// MARK: - ConnectableStream Extensions

public extension ConnectableStream {

  /// Convert connectable stream into the ordinary one by calling `connect`
  /// on first subscription and calling dispose when number of observers goes down to zero.
  public func refCount() -> Stream<T> {
    return Stream(rawStream: self.rawConnectableStream.refCount())
  }
}

// MARK: - PushStream

/// Represents a stream that can push events to registered observers at will.
public class PushStream<T>: StreamType, SubjectType {
  fileprivate let subject = PublishSubject<StreamEvent<T>>()
  fileprivate let disposeBag = DisposeBag()

  public var rawStream: RawStream<StreamEvent<T>> {
    return subject.toRawStream()
  }

  public init() {
  }

  /// Send event to all registered observers.
  public func on(_ event: StreamEvent<T>) {
    subject.on(event)
  }
}

// MARK: - BindableType

/// Bindable is like an observer, but knows to manage the subscription by itself.
public protocol BindableType {
  associatedtype Element

  /// Returns an observer that can be used to dispatch events to the receiver.
  /// Can accept a disposable that will be disposed on receiver's deinit.
  func observer(disconnectDisposable: Disposable) -> ((StreamEvent<Element>) -> Void)
}

extension StreamType {

  /// Establish a one-way binding between the source and the bindable's observer
  /// and return a disposable that can cancel binding.
  @discardableResult
  public func bindTo<B: BindableType>(_ bindable: B) -> Disposable where B.Element == Element {
    let disposable = SerialDisposable(otherDisposable: nil)
    let observer = bindable.observer(disconnectDisposable: disposable)
    disposable.otherDisposable = observe(observer: observer)
    return disposable
  }

  /// Establish a one-way binding between the source and the bindable's observer
  /// and return a disposable that can cancel binding.
  @discardableResult
  public func bindTo<B: BindableType>(_ bindable: B) -> Disposable where B.Element: OptionalType, B.Element.Wrapped == Element {
    let disposable = SerialDisposable(otherDisposable: nil)
    let observer = bindable.observer(disconnectDisposable: disposable)
    disposable.otherDisposable = observe { event in
      switch event {
      case .Next(let element):
        observer(.Next(B.Element(element)))
      case .Completed:
        observer(.Completed)
        disposable.dispose()
      }
    }
    return disposable
  }
}

extension PushStream: BindableType {

  /// Returns an observer that can be used to dispatch events to the receiver.
  /// Can accept a disposable that will be disposed on receiver's deinit.
  public func observer(disconnectDisposable: Disposable) -> (StreamEvent<T>) -> () {
    disposeBag.add(disposable: disconnectDisposable)
    return { [weak self] in self?.on($0) }
  }
}
