name: Build & Test

on: [push]

jobs:
  linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
      - uses: actions/checkout@v1
      - name: Show verion
        run: swift --version
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v

  macOS:
    name: Test on macOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  android:
    name: Test on Android
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test Swift Package on Android
      uses: skiptools/swift-android-action@v2
